steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker build -t gcr.io/polarization-dashboard-dev-1/polis-server:dev ./server
    -f ./server/Dockerfile
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker build -t gcr.io/polarization-dashboard-dev-1/polis-math:dev ./math -f ./math/Dockerfile
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker build -t gcr.io/polarization-dashboard-dev-1/polis-postgres:dev ./server
    -f ./server/Dockerfile-db
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker build -t gcr.io/polarization-dashboard-dev-1/polis-nginx-proxy:dev ./file-server
    -f ./file-server/nginx.Dockerfile
  waitFor:
  - '-'
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - docker build -t gcr.io/polarization-dashboard-dev-1/polis-file-server:dev ./ -f
    ./file-server/Dockerfile
  waitFor:
  - '-'
images:
- gcr.io/polarization-dashboard-dev-1/polis-server:dev
- gcr.io/polarization-dashboard-dev-1/polis-math:dev
- gcr.io/polarization-dashboard-dev-1/polis-postgres:dev
- gcr.io/polarization-dashboard-dev-1/polis-nginx-proxy:dev
- gcr.io/polarization-dashboard-dev-1/polis-file-server:dev
